### PR TITLE
#148 TransactionsViewController crashfix

### LINKED ISSUE #148: 🦟[Bug Report] Crashlytics: TransactionsViewController.swift line 48
**Describe the bug**

Per the info given in Crashlytics there is a recurring crash in TransactionsViewController.swift

## Notes
A quick look suggests the output `PromptType` is an optional and it may be nil in many cases.

## Log

`
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of sections. The number of sections contained in the table view after the update (2) must be equal to the number of sections contained in the table view before the update (2), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted). Table view: <UITableView: 0x108105c00; frame = (0 0; 428 736); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x282502af0>; layer = <CALayer: 0x282b7e4c0>; contentOffset: {0, 0}; contentSize: {428, 5688}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <loafwallet.TransactionsViewController: 0x1036272b0>>
`

## Crashlytics Link
https://console.firebase.google.com/project/litewallet-beta/crashlytics/app/ios:com.litecoin.loafwallet/issues/a0dc29c574d796b2ab76a1975cd69584?time=last-seven-days&sessionEventKey=6cc77f58637845558553d26f913d863a_1741566258082075577
**Screenshots**

**Observed Environment**
 - OS version [e.g. _iOS 13.0_]:
 - Litewallet Version [e.g. _v3.4.0_]:
 - Device model:[e.g. _iPhone 11_]:

**Additional context or information**

### PR DESCRIPTION
**Pull request by Iferencak**

### CODE REVIEW

File: loafwallet/TransactionsViewController.swift [hunk 1]
```diff
@@ -44,7 +44,7 @@ class TransactionsViewController: UIViewController, UITableViewDelegate, UITable
         didSet {
             if currentPromptType != nil && oldValue == nil {
                 tableView.beginUpdates()
-                tableView.insertSections(IndexSet(integer: 0), with: .automatic)
+                tableView.reloadSections(IndexSet(integer: 0), with: .automatic)
```
Comment (kcw-grunt) [inline loafwallet/TransactionsViewController.swift:47]: ooooh. Nice.
Hate that we have to debug UITableView lifecycle...

File: loafwallet/TransactionsViewController.swift [hunk 2]
```diff
@@ -57,10 +57,6 @@ class TransactionsViewController: UIViewController, UITableViewDelegate, UITable
     override func viewDidLoad() {
       setup()
       addSubscriptions()
-
```
Comment (kcw-grunt) [inline loafwallet/TransactionsViewController.swift]: I'm pretty sure I added this because the DispatchQueue  was recommended.
But you removed the            
` self.currentPromptType = .recommendRescan`
 From my recollection means the PromptType is nil.
 
 Is there a  reason why you took it out completely @Iferencak ?

Comment (Iferencak) [reply loafwallet/TransactionsViewController.swift]: This is just a part of a code that I wrote and forgot to remove in the first commit so I did it in the second. It just helped me to trigger a rescan recommended prompt to find out what's wrong. Compared to develop branch, this code did not exist.

File: loafwallet/TransactionsViewController.swift [hunk 3]
```diff
@@ -57,6 +57,10 @@ class TransactionsViewController: UIViewController, UITableViewDelegate, UITable
     override func viewDidLoad() {
       setup()
       addSubscriptions()
+
```
Comment (kcw-grunt) [inline loafwallet/TransactionsViewController.swift]: Yep ...Reviewing the class I think this was my hack to trigger the recommend rescan when hashrate spikes.
I own it.

**Review by kcw-grunt — APPROVED** [review]
